import { expect, it } from 'vitest';
import prePackingRecord from './fixtures/pre-packing-v5.json';
import { replayRecord, runMatch } from './runner';
import { packingReplayRules } from './packing-replay.fixture';
import { validateMatchConfig, validateMatchRecord, validateMatchResult } from '../protocol/validate';
import { MATCH_FORMAT_VERSION, type MatchRecord } from '../protocol/types';
import { applyCommand, createGame, stepGame } from '../sim/game';
import { useLegacyPacking } from '../sim/packing';
import { synchronizationHash } from '../shared/checksum';
import type { GameState } from '../sim/types';

it('replays frozen pre-change v5 pack/unpack and Kataparuto checksums', () => {
  const record = JSON.parse(JSON.stringify(prePackingRecord)) as MatchRecord;
  expect(validateMatchRecord(record)).toBe(true);
  const transitions: [number, boolean][] = [];
  let previous = false;
  const rules = packingReplayRules(), original = JSON.stringify(rules);
  expect(replayRecord(record, rules, state => {
    expect(state.packingVersion).toBeUndefined();
    const treb = state.entities.find(e => e.kind === 'trebuchet');
    if (treb && (treb.unpacked === true) !== previous) {
      previous = treb.unpacked === true;
      transitions.push([state.tick, previous]);
      expect(treb.packingTicks).toBeUndefined();
    }
  })).toEqual({ ok: true, checked: 9 });
  // Captured by the untouched61a2d73 engine, not generated by the code under test.
  expect(transitions).toEqual([[110, true], [230, false], [350, true], [423, false], [483, true], [543, false]]);
  expect(JSON.stringify(rules)).toBe(original);
  // Relabelling an old recording cannot turn it into calibrated playback.
  expect(replayRecord({ ...record, version: MATCH_FORMAT_VERSION }, rules).ok).toBe(false);
});

it('writes the current format even for a v5 launch config and replays calibrated pack/unpack through JSON', async () => {
  expect(MATCH_FORMAT_VERSION).toBeGreaterThanOrEqual(6);
  for (const version of [1, 2, 3, 4, 5, 6, 7, 8]) expect(validateMatchConfig({ version, seed: 259 })).toBe(true);
  expect(validateMatchConfig({ version: MATCH_FORMAT_VERSION + 1, seed: 259 })).toBe(false);
  const rules = packingReplayRules();
  const { record, result } = await runMatch({ version: 5, seed: 259, maxTimeSeconds: 45, decideIntervalSeconds: .05 }, {
    1: { decide: ({ observation: o }) => {
      const tick = Math.round(o.time * 20);
      const tc = o.entities.find(e => e.owner === 1 && e.kind === 'town-center')!;
      if (tick === 0) return [{ kind: 'train', player: 1, buildingId: tc.id, unit: 'trebuchet' }];
      if (tick === 580) return [{ kind: 'research', player: 1, buildingId: tc.id, tech: 'kataparuto' }];
      if (![20, 300, 620, 740].includes(tick)) return [];
      const treb = o.entities.find(e => e.owner === 1 && e.kind === 'trebuchet')!;
      return [{ kind: 'pack', player: 1, entityIds: [treb.id], unpacked: tick === 20 || tick === 620 }];
    } }, 2: { decide: () => [] },
  }, rules);
  expect(record.version).toBe(MATCH_FORMAT_VERSION); expect(result.version).toBe(MATCH_FORMAT_VERSION);
  expect(result.rejectedCommands).toEqual([]);
  expect(validateMatchResult(result)).toBe(true);
  const wire = JSON.parse(JSON.stringify(record));
  expect(validateMatchRecord(wire)).toBe(true);
  const transitions: [number, boolean][] = []; let previous = false;
  expect(replayRecord(wire, rules, state => {
    expect(state.packingVersion).toBe(1);
    const treb = state.entities.find(e => e.kind === 'trebuchet');
    if (treb && (treb.unpacked === true) !== previous) {
      previous = treb.unpacked === true; transitions.push([state.tick, previous]);
      expect(treb.packingTicks).toBeUndefined();
    }
  })).toEqual({ ok: true, checked: 9 });
  expect(transitions).toEqual([[242, true], [522, false], [676, true], [796, false]]);
});

it.each([false, true])('preserves embedded packing rules/timers through JSON (legacy=%s)', legacy => {
  const state = createGame(259, packingReplayRules());
  if (legacy) useLegacyPacking(state);
  const tc = state.entities.find(e => e.owner === 1 && e.kind === 'town-center')!;
  expect(applyCommand(state, { kind: 'train', player: 1, buildingId: tc.id, unit: 'trebuchet' }).ok).toBe(true);
  stepGame(state);
  const treb = state.entities.find(e => e.kind === 'trebuchet')!;
  expect(applyCommand(state, { kind: 'pack', player: 1, entityIds: [treb.id], unpacked: true }).ok).toBe(true);
  for (let i = 0; i < 20; i++) stepGame(state);
  const resumed: GameState = JSON.parse(JSON.stringify(state));
  const remaining = (legacy ? 90 : 222) - 20;
  expect(treb.packingTicks).toBe(remaining);
  for (let i = 0; i < remaining; i++) { stepGame(state); stepGame(resumed); }
  for (const game of [state, resumed]) {
    const completed = game.entities.find(e => e.id === treb.id)!;
    expect(game.packingVersion).toBe(legacy ? undefined : 1);
    expect(completed.unpacked).toBe(true); expect(completed.packingTicks).toBeUndefined();
    expect(applyCommand(game, { kind: 'pack', player: 1, entityIds: [treb.id], unpacked: false }).ok).toBe(true);
    expect(completed.packingTicks).toBe(legacy ? 90 : 222);
  }
  expect(synchronizationHash(resumed)).toBe(synchronizationHash(state));
});
