import { expect, it } from 'vitest';
import preSiphonsRecord from './fixtures/pre-siphons-v6.json';
import { replayRecord, runMatch } from './runner';
import { siphonsReplayRules } from './siphons-replay.fixture';
import { MATCH_FORMAT_VERSION, type MatchRecord } from '../protocol/types';
import { validateMatchConfig, validateMatchRecord, validateMatchResult } from '../protocol/validate';
import { applyCommand, createGame, stepGame } from '../sim/game';
import { synchronizationHash } from '../shared/checksum';
import type { GameState } from '../sim/types';

it('replays frozen pre-change v6 charged Fire Galley building attacks', () => {
  const record = JSON.parse(JSON.stringify(preSiphonsRecord)) as MatchRecord;
  expect(validateMatchRecord(record)).toBe(true);
  const rules = siphonsReplayRules(), original = JSON.stringify(rules);
  let firstChargeTick: number | undefined;
  expect(replayRecord(record, rules, state => {
    expect(state.siphonsVersion).toBeUndefined();
    const shot = state.projectiles.find(p => p.art === 'fire-charge');
    if (shot && firstChargeTick === undefined) {
      firstChargeTick = state.tick;
      expect(state.entities.find(e => e.id === shot.targetId)?.kind).toBe('town-center');
      expect(state.entities.find(e => e.id === shot.shooterId)?.charge).toBe(0);
    }
  })).toEqual({ ok: true, checked: 4 });
  // Captured by untouched98979f6, not generated by the implementation under test.
  expect(firstChargeTick).toBe(21);
  expect(JSON.stringify(rules)).toBe(original);
  expect(replayRecord({ ...record, version: MATCH_FORMAT_VERSION }, rules).ok).toBe(false);
});

it('writes the current format for a v6 launch and replays building attacks without charge expenditure', async () => {
  expect(MATCH_FORMAT_VERSION).toBeGreaterThanOrEqual(7);
  for (const version of [1, 2, 3, 4, 5, 6, 7, 8]) expect(validateMatchConfig({ version, seed: 242 })).toBe(true);
  expect(validateMatchConfig({ version: MATCH_FORMAT_VERSION + 1, seed: 242 })).toBe(false);
  const prior = preSiphonsRecord as MatchRecord, rules = siphonsReplayRules();
  const { record, result } = await runMatch({ version: 6, seed: 242, maxTimeSeconds: 20, decideIntervalSeconds: .05 }, {
    1: { decide: ({ observation: o }) => prior.commands.filter(c => c.tick === Math.round(o.time * 20)).map(c => c.command) },
    2: { decide: () => [] },
  }, rules);
  expect(record.version).toBe(MATCH_FORMAT_VERSION); expect(result.version).toBe(MATCH_FORMAT_VERSION);
  expect(result.rejectedCommands).toEqual([]);
  expect(validateMatchResult(result)).toBe(true);
  const wire = JSON.parse(JSON.stringify(record));
  expect(validateMatchRecord(wire)).toBe(true);
  let ordinaryShot = false;
  expect(replayRecord(wire, rules, state => {
    expect(state.siphonsVersion).toBe(1);
    expect(state.projectiles.some(p => p.art === 'fire-charge')).toBe(false);
    const ship = state.entities.find(e => e.kind === 'fire-galley');
    if (ship) {
      expect(ship.charge ?? 1).toBe(1);
      ordinaryShot ||= state.projectiles.some(p => p.shooterId === ship.id && p.targetId === 6);
    }
  })).toEqual({ ok: true, checked: 4 });
  expect(ordinaryShot).toBe(true);
  expect(replayRecord({ ...wire, version: 6 }, rules).ok).toBe(false);
});

it.each([false, true])('continues JSON snapshots without retrofitting the charge policy (legacy=%s)', legacy => {
  const state = createGame(242, siphonsReplayRules());
  if (legacy) delete state.siphonsVersion;
  const record = preSiphonsRecord as MatchRecord;
  expect(applyCommand(state, record.commands[0].command).ok).toBe(true);
  for (let i = 0; i < 20; i++) stepGame(state);
  expect(applyCommand(state, record.commands[1].command).ok).toBe(true);
  let resumed: GameState = JSON.parse(JSON.stringify(state));
  for (let i = 0; i < 100; i++) {
    stepGame(state); stepGame(resumed);
    for (const game of [state, resumed]) {
      expect(game.siphonsVersion).toBe(legacy ? undefined : 1);
      const ship = game.entities.find(e => e.kind === 'fire-galley')!;
      expect((ship.charge ?? 1) < 1).toBe(legacy);
      expect(game.projectiles.some(p => p.art === 'fire-charge')).toBe(legacy);
    }
    expect(synchronizationHash(resumed)).toBe(synchronizationHash(state));
    // Save again with legacy charge already spent and its projectile in flight.
    if (i === 0) resumed = JSON.parse(JSON.stringify(resumed));
  }
});
