import { describe, expect, it } from 'vitest';
import { FALLBACK_RULES, isBuilding } from './data';
import { applyCommand, createGame, stepGame, unitRulesFor, buildingRulesFor, useLegacyTrebuchetTargeting } from './game';
import { calculateScore, resourceValue, assetScore, useLegacyScore } from './score';
import { useLegacyPacking } from './packing';
import { useLegacySiphons } from './fire-charge';
import { observe } from './observe';
import { updateVisibility } from './visibility';
import { checksumState } from './checksum';
import { synchronizationHash } from '../shared/checksum';
import { validateObservation } from '../protocol/validate';
import { replayRecord, runMatch } from '../headless/runner';
import { MATCH_FORMAT_VERSION } from '../protocol/types';
import type { BuildingKind, Command, Entity, GameState, PlayerId, UnitKind } from './types';

function fixture() {
  const rules = structuredClone(FALLBACK_RULES);
  rules.units.villager.trainSeconds = .1;
  for (const rule of Object.values(rules.buildings)) rule.buildSeconds = .1;
  rules.technologies.loom.researchSeconds = .1;
  rules.units.monk.convert = { minSeconds: .1, maxSeconds: .1, range: 9 };
  const state = createGame(139, rules);
  state.entities = state.entities.filter(e => e.kind === 'town-center' || e.kind === 'villager');
  state.terrain.fill(0); state.elevation.fill(0);
  for (const id of [1, 2] as const) {
    Object.assign(state.players[id], { food: 2000, wood: 2000, gold: 2000, stone: 2000 });
    // Hold exploration fixed except in its dedicated command-driven test.
    state.visibility[id].explored.fill(1);
  }
  return state;
}
const tc = (s: GameState, owner: PlayerId = 1) => s.entities.find(e => e.owner === owner && e.kind === 'town-center')!;
const score = (s: GameState, owner: PlayerId = 1) => calculateScore(s, owner);
function command(s: GameState, c: Command) {
  updateVisibility(s);
  expect(applyCommand(s, c)).toEqual({ ok: true });
}
function until(s: GameState, done: () => boolean, limit = 500) {
  for (let i = 0; i < limit && !done(); i++) stepGame(s);
  expect(done()).toBe(true);
}
function spawn(s: GameState, kind: UnitKind | BuildingKind, owner: Entity['owner'], x = 60.5, y = 50.5) {
  const rules = isBuilding(kind) ? buildingRulesFor(s, owner, kind) : unitRulesFor(s, owner, kind);
  const entity: Entity = { id: s.nextId++, kind, owner, position: { x, y }, hp: rules.hp,
    maxHp: rules.hp, radius: rules.radius, activity: 'idle', order: { kind: 'idle' } };
  s.entities.push(entity);
  return entity;
}
function build(s: GameState, kind: BuildingKind) {
  const worker = s.entities.find(e => e.owner === 1 && e.kind === 'villager')!;
  worker.position = { x: 43, y: 40.5 };
  const id = s.nextId;
  command(s, { kind: 'build', player: 1, building: kind, builderIds: [worker.id], target: { x: 40.5, y: 40.5 } });
  return s.entities.find(e => e.id === id)!;
}
function attack(s: GameState, attacker: Entity, victim: Entity) {
  command(s, { kind: 'order', player: attacker.owner as PlayerId, entityIds: [attacker.id],
    target: victim.position, targetId: victim.id });
  until(s, () => !!victim.dead);
}

describe('manual-derived public score (#139)', () => {
  it('preserves actual pre-score v3 hashes through paid training/research, while new records replay score state', async () => {
    const rules = structuredClone(FALLBACK_RULES);
    rules.units.villager.trainSeconds = .1;
    rules.technologies.loom.researchSeconds = .1;
    const s = createGame(139, rules, undefined, 'arabia', undefined, undefined, undefined, 0); useLegacyScore(s);
    useLegacyPacking(s);
    useLegacySiphons(s);
    useLegacyTrebuchetTargeting(s);
    const commands: Command[] = [
      { kind: 'train', player: 1, buildingId: tc(s).id, unit: 'villager' },
      { kind: 'research', player: 1, buildingId: tc(s).id, tech: 'loom' },
    ];
    for (const c of commands) expect(applyCommand(s, c).ok).toBe(true);
    // Independently measured from unmodified eff7292, not regenerated by this implementation.
    const hashes = [{ tick: 1, hash: '1b4d93c5' }, { tick: 5, hash: '6c7161cd' }, { tick: 20, hash: '39841730' }];
    for (const expected of hashes) {
      until(s, () => s.tick === expected.tick);
      expect(checksumState(s)).toBe(expected.hash);
    }
    expect(s.players[1].scoreSpentOnResearch).toBeUndefined();
    const { record } = await runMatch({ version: 4, seed: 139, maxTimeSeconds: 5 }, {
      1: { decide: ({ observation }) => observation.time === 0 ? commands : [] }, 2: { decide: () => [] },
    }, rules);
    expect(record.version).toBe(MATCH_FORMAT_VERSION);
    expect(record.checksums.length).toBeGreaterThan(0);
    let replayed: GameState | undefined;
    const replay = replayRecord(record, rules, state => { replayed = state; });
    expect(replay.ok).toBe(true);
    expect(replay.checked).toBeGreaterThan(0);
    expect(replay.checked).toBe(record.checksums.length);
    expect(replayed!.players[1].researched).toContain('loom');
    expect(replayed!.players[1].scoreSpentOnResearch).toBe(resourceValue(rules.technologies.loom.cost));
    expect(tc(replayed!).training).toBeUndefined();
    const villagers = replayed!.entities.filter(e => e.owner === 1 && e.kind === 'villager');
    expect(villagers).toHaveLength(4);
    expect(villagers.at(-1)!.scorePaidCost).toBe(resourceValue(rules.units.villager.cost));
    expect(replayRecord({ ...record, version: 3, checksums: hashes }, rules)).toEqual({ ok: true, checked: 3 });
  });
  it('values stockpile at 0.1, absent counters at zero, without mutating legacy JSON', () => {
    const s = fixture(); s.entities = [];
    s.visibility[1].explored.fill(0);
    Object.assign(s.players[1], { food: 123, wood: 200, gold: 300, stone: 400 });
    const before = checksumState(s);
    expect(score(s)).toEqual({ economy: 102.3, military: 0, technology: 0, society: 0, total: 102 });
    expect(checksumState(s)).toBe(before);
    expect(score(JSON.parse(JSON.stringify(s)))).toEqual(score(s));
  });

  it('training spends stockpile once, credits 0.2 on emergence, retains the paid discounted price', () => {
    const s = fixture();
    s.rules.technologies['fixture-discount'] = { techId: 9999, name: 'fixture', researchedAt: 'town-center',
      requiresAge: 0, researchSeconds: .1, cost: { food: 0, wood: 0, gold: 0, stone: 0 },
      effects: [{ unit: 'villager', attribute: 'foodCost', operation: 'multiply', amount: .5 }] };
    command(s, { kind: 'research', player: 1, buildingId: tc(s).id, tech: 'fixture-discount' });
    until(s, () => s.players[1].researched.includes('fixture-discount'));
    const before = score(s).economy, id = s.nextId, food = s.players[1].food;
    command(s, { kind: 'train', player: 1, buildingId: tc(s).id, unit: 'villager' });
    const paid = food - s.players[1].food;
    expect(paid).toBe(25);
    expect(score(s).economy).toBeCloseTo(before - paid * .1);
    until(s, () => s.entities.some(e => e.id === id));
    expect(score(s).economy).toBeCloseTo(before + paid * .1);
    expect(s.entities.find(e => e.id === id)!.scorePaidCost).toBe(paid);
    // A later quote change must not revalue the completed asset.
    s.rules.units.villager.cost.food = 200;
    expect(assetScore(s, s.entities.find(e => e.id === id)!)).toBe(5);
  });

  it.each(['house', 'castle', 'wonder'] as const)('credits a completed %s in the sourced column, then removes it on Delete', kind => {
    const s = fixture(); s.players[1].age = 3;
    const before = score(s), purse = resourceValue(s.players[1]);
    const site = build(s, kind), paid = purse - resourceValue(s.players[1]);
    expect(site.scorePaidCost).toBe(paid);
    expect(assetScore(s, site)).toBe(0);
    until(s, () => site.buildProgress === undefined);
    const category = kind === 'house' ? 'economy' : 'society';
    expect(score(s)[category] - before[category]).toBeCloseTo(paid * (kind === 'house' ? .1 : .2));
    const completed = score(s)[category];
    command(s, { kind: 'delete', player: 1, entityIds: [site.id] });
    expect(score(s)[category]).toBeCloseTo(completed - paid * .2);
    expect(score(s).military).toBe(before.military);
  });

  it('research credits raw paid cost once, including a JSON resume with queued work', () => {
    const s = fixture(), before = score(s), purse = resourceValue(s.players[1]);
    command(s, { kind: 'research', player: 1, buildingId: tc(s).id, tech: 'loom' });
    const paid = purse - resourceValue(s.players[1]);
    expect(score(s).technology).toBe(before.technology);
    const clone: GameState = JSON.parse(JSON.stringify(s));
    until(s, () => s.players[1].researched.includes('loom'));
    until(clone, () => clone.players[1].researched.includes('loom'));
    expect(score(s).technology).toBeCloseTo(before.technology + paid * .2);
    expect(score(s).economy).toBeCloseTo(before.economy - paid * .1);
    expect(s.players[1].scoreSpentOnResearch).toBe(paid);
    expect(score(clone)).toEqual(score(s));
    expect(synchronizationHash(clone)).toBe(synchronizationHash(s));
    const changed: GameState = JSON.parse(JSON.stringify(s));
    changed.players[1].scoreSpentOnResearch!++;
    expect(synchronizationHash(changed)).not.toBe(synchronizationHash(s));
    stepGame(s); stepGame(clone);
    expect(synchronizationHash(clone)).toBe(synchronizationHash(s));
    expect(s.players[1].scoreSpentOnResearch).toBe(paid);
  });

  it('active and waiting unit/research cancels refund without production score', () => {
    const s = fixture(), before = score(s);
    for (let i = 0; i < 2; i++) command(s, { kind: 'train', player: 1, buildingId: tc(s).id, unit: 'villager' });
    command(s, { kind: 'research', player: 1, buildingId: tc(s).id, tech: 'loom' });
    command(s, { kind: 'research', player: 1, buildingId: tc(s).id, tech: 'feudal-age' });
    for (const kind of ['cancel-train', 'cancel-research'] as const) {
      command(s, { kind, player: 1, buildingId: tc(s).id, index: 1 });
      command(s, { kind, player: 1, buildingId: tc(s).id, index: 0 });
    }
    stepGame(s);
    expect(score(s)).toEqual(before);
    expect(s.players[1].scoreSpentOnResearch).toBeUndefined();
    expect(applyCommand(s, { kind: 'cancel-research', player: 1, buildingId: tc(s).id }).ok).toBe(false);
    expect(score(s)).toEqual(before);
  });

  it.each(['villager', 'house', 'castle'] as const)('transfers exactly 0.2 of enemy %s value on a kill, once', kind => {
    const s = fixture(), killer = spawn(s, 'militia', 1, 60, 50.5), victim = spawn(s, kind, 2, 60.5, 50.5);
    killer.position.x = victim.position.x - victim.radius - killer.radius - .1;
    victim.hp = 1;
    const value = assetScore(s, victim), before = score(s), enemy = score(s, 2);
    attack(s, killer, victim);
    expect(score(s).military - before.military).toBeCloseTo(value);
    const category = kind === 'castle' ? 'society' : 'economy';
    expect(enemy[category] - score(s, 2)[category]).toBeCloseTo(value);
    stepGame(s);
    expect(score(s).military - before.military).toBeCloseTo(value);
  });

  it('conversion and recapture transfer the held value, never create a second economic award', () => {
    const s = fixture(), monk = spawn(s, 'monk', 1, 57.5), victim = spawn(s, 'militia', 2);
    const value = assetScore(s, victim), before = score(s), enemy = score(s, 2);
    command(s, { kind: 'order', player: 1, entityIds: [monk.id], target: victim.position, targetId: victim.id });
    until(s, () => victim.owner === 1);
    expect(score(s).military - before.military).toBeCloseTo(value);
    expect(score(s).economy).toBe(before.economy);
    expect(enemy.economy - score(s, 2).economy).toBeCloseTo(value);
    const other = spawn(s, 'monk', 2, 63.5);
    const captured = score(s), donor = score(s, 2);
    command(s, { kind: 'order', player: 2, entityIds: [other.id], target: victim.position, targetId: victim.id });
    until(s, () => victim.owner === 2);
    expect(captured.military - score(s).military).toBeCloseTo(value);
    expect(score(s, 2).military - donor.military).toBeCloseTo(value);
    expect(score(JSON.parse(JSON.stringify(s)), 2)).toEqual(score(s, 2));
  });

  it('Gaia hunting awards no military score and deleting your own unit does not reward the opponent', () => {
    const s = fixture(), hunter = spawn(s, 'militia', 1, 60, 50.5), deer = spawn(s, 'deer', 0);
    deer.amount = 140; deer.resourceKind = 'food';
    deer.hp = 1;
    const before = score(s).military;
    attack(s, hunter, deer);
    expect(score(s).military).toBe(before);
    const own = score(s).economy, enemy = score(s, 2), value = assetScore(s, hunter);
    command(s, { kind: 'delete', player: 1, entityIds: [hunter.id] });
    expect(own - score(s).economy).toBeCloseTo(value);
    expect(score(s, 2)).toEqual(enemy);
  });

  it('movement explores permanently for 10 points per percent in Technology, including JSON/public totals', () => {
    const s = fixture(), scout = spawn(s, 'scout-cavalry', 1, 40.5, 40.5);
    s.visibility[1].explored.fill(0); updateVisibility(s);
    const before = score(s).technology;
    command(s, { kind: 'order', player: 1, entityIds: [scout.id], target: { x: 48.5, y: 40.5 } });
    until(s, () => scout.position.x > 47);
    const explored = s.visibility[1].explored.reduce((n, v) => n + v, 0);
    expect(score(s).technology).toBeGreaterThan(before);
    expect(score(s).technology).toBe(explored * 1000 / (s.width * s.height));
    const beforeRead = synchronizationHash(s);
    for (const player of [1, 2] as const) {
      const o = JSON.parse(JSON.stringify(observe(s, player)));
      expect(validateObservation(o)).toBe(true);
      expect(o.scores).toEqual({ 1: score(s).total, 2: score(s, 2).total });
      expect(Object.keys(o.scores)).toEqual(['1', '2']);
    }
    expect(synchronizationHash(s)).toBe(beforeRead);
  });

  it('retains a foundation receipt through a later price change and awards nothing for a deleted foundation', () => {
    const s = fixture(), before = score(s).economy;
    s.rules.buildings.house.cost.wood = 13;
    const site = build(s, 'house');
    expect(site.scorePaidCost).toBe(13);
    s.rules.buildings.house.cost.wood = 200;
    until(s, () => site.buildProgress === undefined);
    expect(score(s).economy - before).toBeCloseTo(1.3);
    command(s, { kind: 'delete', player: 1, entityIds: [site.id] });
    const next = build(s, 'house'), placed = score(s);
    command(s, { kind: 'delete', player: 1, entityIds: [next.id] });
    expect(score(s)).toEqual(placed); // Delete is not a construction refund.
  });

  it('research uses the paid discount even if the current quote changes before completion', () => {
    const s = fixture();
    s.rules.playerAttributes = { ...s.rules.playerAttributes, researchCostMod: .5 };
    const before = score(s), purse = resourceValue(s.players[1]);
    command(s, { kind: 'research', player: 1, buildingId: tc(s).id, tech: 'loom' });
    const paid = purse - resourceValue(s.players[1]);
    expect(paid).toBe(25);
    s.rules.playerAttributes.researchCostMod = 1;
    until(s, () => s.players[1].researched.includes('loom'));
    expect(score(s).technology - before.technology).toBe(5);
  });

  it('garrisoning and ungarrisoning a paid unit do not change its score', () => {
    const s = fixture(), home = tc(s);
    const worker = s.entities.find(e => e.owner === 1 && e.kind === 'villager')!;
    const before = score(s);
    command(s, { kind: 'order', player: 1, entityIds: [worker.id], target: home.position, targetId: home.id });
    until(s, () => !!home.garrison?.length);
    expect(score(s)).toEqual(before);
    command(s, { kind: 'ungarrison', player: 1, buildingId: home.id });
    expect(score(s)).toEqual(before);
  });

  it('self-destruction removes its own asset and credits enemy splash victims, not friendly fire', () => {
    const s = fixture();
    Object.assign(s.rules.units.petard, { attackReleaseSeconds: 0, blastRadius: 4,
      attacks: [{ class: 4, amount: 1000 }, { class: 11, amount: 1000 }] });
    const petard = spawn(s, 'petard', 1, 57.5), target = spawn(s, 'house', 2);
    const bystander = spawn(s, 'militia', 2, 58, 52), friendly = spawn(s, 'militia', 1, 57, 52);
    target.hp = 1; bystander.hp = 1;
    const before = score(s), enemy = score(s, 2);
    const value = assetScore(s, target) + assetScore(s, bystander), lost = assetScore(s, petard);
    attack(s, petard, target);
    expect(petard.dead).toBe(true); expect(bystander.dead).toBe(true); expect(friendly.dead).not.toBe(true);
    expect(score(s).military - before.military).toBeCloseTo(value);
    expect(before.economy - score(s).economy).toBeCloseTo(lost);
    expect(enemy.economy - score(s, 2).economy).toBeCloseTo(value);
  });

  it('an armed building earns the same kill credit as a unit', () => {
    const s = fixture(), tower = spawn(s, 'watch-tower', 1, 55.5), enemy = spawn(s, 'militia', 2);
    enemy.hp = 1;
    const value = assetScore(s, enemy), before = score(s).military;
    attack(s, tower, enemy);
    expect(score(s).military - before).toBeCloseTo(value);
  });
});
